### ISSUE TITLE
About the connection between RPI and Lidar

### ISSUE THREAD

**Issue by JINGJAN** [drwnz/rpi_sensor_sync#4]
Hi!
I am doing some similar work, trying to do time Synchronization between different lidars.
You have introduced your Prerequisites Hardware. However, I don't know, which **cable you used to connect the GPS port** of the Lidar. If possible could you give me some suggestions?
Thank you very much!
![power_ethernet_gps_box](https://user-images.githubusercontent.com/38492507/157301487-d4ba0b91-1e78-482f-93e2-50cd356d665b.jpg)
Best regards,
Jing

**Comment by drwnz** [comment]
Velodyne supplies a Garmin GPS with a matching cable for the GPS port on the interface box.
However, if you want to sync with GNS, I would suggest modifying it or making your own - as the RPi will also need a 1PPS signal from the GNSS. 
Or, you can connect a GPS receiver 1PPS only to the RPi and then make a cable to use a GPIO from the RPi to feed the GPS 1PPS to the interface box through the GPS port.

**Comment by JINGJAN** [comment]
Hi drwnz, 
**Thanks very much for this info!**
I have found a suitable Cable(SH 1.0 mm 6 pin) to connect the GPS port on the interface box. 
Now I don't want to use an external GPS receiver, because sometimes the GPS signal works not well. 
You have mentioned in your project:
 "Case 1: No GNSS available, synchronization of LiDAR(s) and camera(s)".
I think this case is similar to my task, I need to generate Fake PPS and NMEA messages to the Velodyne lidar through the GPS port.
Thanks again for your reply and your project! Keep in touch.
