### ISSUE TITLE
Acquiring the output

### ISSUE THREAD

**Issue by ankitadey905** [drwnz/rpi_sensor_sync#5]
Hello, this may be trivial but how will one collect the output from the sensors triggered by this repository?

**Comment by drwnz** [comment]
@ankitadey905 the sensor output is collected independently of this system - The RPi only controls synchronization between sensors.

**Comment by ankitadey905** [comment]
Thank you for your reply. Can you suggest some ways of collecting the output?

**Comment by drwnz** [comment]
If you are using a Velodyne sensor, I would suggest using the Velodyne ROS driver and collect data in ROS.
Although it is possible on the RPi, I think it is easier to collect data on a separate machine (as using ROS on the RPi involves a bit more setup).

**Comment by ankitadey905** [comment]
Thank you for the suggestion. Appreciate the prompt reply.
